angular.module('app').constant('configuration', {
    siteName: '@@siteName',
    facebookApiToken: '@@facebookApiToken',
    mixpanelApiToken: '@@mixpanelApiToken',
    serverHostName: '@@serverHostName',
    serverProtocol: '@@serverProtocol',
    serverPort: '@@serverPort',
    serverContext: '@@serverContext',
    serverWebSocketContext: '@@serverWebSocketContext',
    serverWebServicesContext: '@@serverWebServicesContext',
    baseUrl: '@@serverProtocol://@@serverHostName:@@serverPort@@serverContext',
    websocketBaseUrl: '@@serverProtocol://@@serverHostName:@@serverPort@@serverWebSocketContext',
    webservicesBaseUrl: '@@serverProtocol://@@serverHostName:@@serverPort@@serverWebServicesContext',
    version: '@@version',
    mailchimpUsername: '@@mailchimpUsername',
    mailchimpU: '@@mailchimpU',
    mailchimpDc: '@@mailchimpDc',
    mailchimpId: '@@mailchimpId'
  });
