angular.module('app').constant('configuration', {
    siteName: 'Bearchoke Tempest',
    facebookApiToken: '1406544132926146',
    mixpanelApiToken: 'af496858fbad6db085f002140fd3c9e1',
    serverHostName: 'dev.bearchoke.com',
	websocketServerHostName: 'dev.bearchoke.com',
    serverProtocol: 'http',
    serverPort: '8080',
	websocketServerPort: '8080',
    serverContext: '/api',
    serverWebSocketContext: '/ws',
    serverWebServicesContext: '/services',
    baseUrl: 'http://dev.bearchoke.com:8080/api',
    websocketBaseUrl: 'http://dev.bearchoke.com:8080/ws',
    webservicesBaseUrl: 'http://dev.bearchoke.com:8080/services',
    version: 'application/vnd.bearchoke-v1+json',
    mailchimpUsername: 'cfapps',
    mailchimpU: '6e09b949dd8c5be5b4befdfeb',
    mailchimpDc: 'us9',
    mailchimpId: '670f539e60'
  });
